apiVersion: apps/v1
kind: Deployment
metadata:
  name: playbook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playbook-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: playbook-service
    spec:
      containers:
        - name: playbook-service
          image: outoftheparkacr.azurecr.io/playbook-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: playbook-http
---
apiVersion: v1
kind: Service
metadata:
  name: playbook-service-deployment
spec:
  ports:
    - name: playbook-service
      port: 80
      targetPort: playbook-http
  selector:
    app: playbook-service
  type: ClusterIP